import { Hospital, BlogRequest, User, FormatType, ChatMessage } from '@/types';

// Mock 병원 데이터
export const mockHospitals: Hospital[] = [
  {
    hospital_id: 'H001',
    hospital_name: '좋은문화병원 림프부종센터',
    system_prompt: '병원 마케팅을 위한 블로그 글 작성 가이드...',
    reference_folder_id: '1a2b3c4d5e',
    output_folder_id: '1f43iS-hel0wSDZs7KheVoXC5oaykhVGk',
    slack_channel: '#blog-lymphedema',
    created_at: '2025-01-01T09:00:00',
    updated_at: '2025-01-10T14:30:00',
  },
  {
    hospital_id: 'H002',
    hospital_name: 'B피부과의원',
    system_prompt: '피부과 전문 블로그 작성 가이드...',
    reference_folder_id: '2b3c4d5e6f',
    output_folder_id: '6f5e4d3c2b',
    slack_channel: '#blog-derma',
    created_at: '2025-01-05T10:00:00',
    updated_at: '2025-01-08T16:00:00',
  },
  {
    hospital_id: 'H003',
    hospital_name: 'C정형외과',
    system_prompt: '정형외과 전문 블로그 작성 가이드...',
    reference_folder_id: '3c4d5e6f7g',
    output_folder_id: '7g6f5e4d3c',
    slack_channel: '#blog-ortho',
    created_at: '2025-01-07T11:00:00',
    updated_at: '2025-01-12T09:00:00',
  },
];

// Mock 요청 데이터
export const mockRequests: BlogRequest[] = [
  {
    request_id: 'R20250112001',
    created_at: '2025-01-12T14:30:00',
    hospital_id: 'H001',
    hospital_name: '좋은문화병원 림프부종센터',
    target_keyword: '유방암수술후부종',
    topic_keyword: '바이오브릿지 수술',
    purpose: '유방암 수술 후 림프부종으로 인해 지속적인 고통을 겪는 환자들에게 근본적인 치료 방법, 그 중에서도 바이오브릿지를 중점적으로 어필',
    format_type: '팩트체크형',
    status: '완료',
    result_doc_id: 'doc123abc',
    result_doc_url: 'https://docs.google.com/document/d/doc123abc',
    revision_count: 0,
    completed_at: '2025-01-12T14:35:00',
    created_by: 'staff@company.com',
    chat_history: [
      {
        id: 'msg001',
        role: 'system',
        content: '블로그 글 생성을 시작합니다.\n\n**타겟 키워드:** 유방암수술후부종\n**주제:** 바이오브릿지 수술\n**구조:** 팩트체크형',
        created_at: '2025-01-12T14:30:00',
      },
      {
        id: 'msg002',
        role: 'assistant',
        content: '블로그 글 초안을 완성했습니다.\n\n유방암 수술 후 림프부종에 대한 팩트체크형 글을 작성했습니다. 바이오브릿지 수술의 원리, 효과, 그리고 실제 치료 사례를 중심으로 구성했습니다.\n\n문서를 확인해주시고, 수정이 필요한 부분이 있으면 말씀해주세요.',
        created_at: '2025-01-12T14:35:00',
        doc_url: 'https://docs.google.com/document/d/doc123abc',
        doc_id: 'doc123abc',
      },
    ],
  },
  {
    request_id: 'R20250112002',
    created_at: '2025-01-12T15:00:00',
    hospital_id: 'H002',
    hospital_name: 'B피부과의원',
    target_keyword: '여드름흉터치료',
    topic_keyword: '프락셀 레이저',
    purpose: '여드름 흉터로 고민하는 20-30대 환자들에게 프락셀 레이저 치료의 효과와 과정을 설명',
    format_type: '사례/스토리텔링형',
    status: '생성중',
    revision_count: 0,
    created_by: 'staff2@company.com',
    chat_history: [
      {
        id: 'msg003',
        role: 'system',
        content: '블로그 글 생성을 시작합니다.\n\n**타겟 키워드:** 여드름흉터치료\n**주제:** 프락셀 레이저\n**구조:** 사례/스토리텔링형',
        created_at: '2025-01-12T15:00:00',
      },
    ],
  },
  {
    request_id: 'R20250112003',
    created_at: '2025-01-12T15:30:00',
    hospital_id: 'H001',
    hospital_name: '좋은문화병원 림프부종센터',
    target_keyword: '림프부종치료',
    topic_keyword: '복합림프물리치료',
    purpose: '림프부종 환자들에게 비수술적 치료 방법인 복합림프물리치료의 효과를 안내',
    format_type: 'Q&A형',
    status: '대기',
    revision_count: 0,
    created_by: 'staff@company.com',
    chat_history: [],
  },
  {
    request_id: 'R20250111001',
    created_at: '2025-01-11T10:00:00',
    hospital_id: 'H003',
    hospital_name: 'C정형외과',
    target_keyword: '무릎연골손상',
    topic_keyword: '줄기세포치료',
    purpose: '무릎 연골 손상 환자들에게 줄기세포 치료의 장점과 회복 과정을 설명',
    format_type: '비교분석형',
    status: '완료',
    result_doc_id: 'doc456def',
    result_doc_url: 'https://docs.google.com/document/d/doc456def',
    revision_count: 1,
    revision_request: '두번째 문단의 톤을 좀 더 친근하게 수정해주세요',
    completed_at: '2025-01-11T10:45:00',
    created_by: 'staff3@company.com',
    chat_history: [
      {
        id: 'msg004',
        role: 'system',
        content: '블로그 글 생성을 시작합니다.\n\n**타겟 키워드:** 무릎연골손상\n**주제:** 줄기세포치료\n**구조:** 비교분석형',
        created_at: '2025-01-11T10:00:00',
      },
      {
        id: 'msg005',
        role: 'assistant',
        content: '블로그 글 초안을 완성했습니다.\n\n무릎 연골 손상에 대한 비교분석형 글을 작성했습니다. 기존 치료법과 줄기세포 치료를 비교하며, 각각의 장단점을 객관적으로 설명했습니다.',
        created_at: '2025-01-11T10:20:00',
        doc_url: 'https://docs.google.com/document/d/doc456def_v1',
        doc_id: 'doc456def_v1',
      },
      {
        id: 'msg006',
        role: 'user',
        content: '두번째 문단의 톤을 좀 더 친근하게 수정해주세요',
        created_at: '2025-01-11T10:30:00',
      },
      {
        id: 'msg007',
        role: 'assistant',
        content: '두번째 문단의 톤을 더 친근하게 수정했습니다.\n\n"전문적인 의학 용어" 대신 "쉬운 일상 표현"을 사용하고, 환자분들이 공감할 수 있는 예시를 추가했습니다. 확인해주세요!',
        created_at: '2025-01-11T10:45:00',
        doc_url: 'https://docs.google.com/document/d/doc456def',
        doc_id: 'doc456def',
      },
    ],
  },
  {
    request_id: 'R20250111002',
    created_at: '2025-01-11T14:00:00',
    hospital_id: 'H002',
    hospital_name: 'B피부과의원',
    target_keyword: '기미치료',
    topic_keyword: '피코레이저',
    purpose: '기미로 고민하는 환자들에게 피코레이저 치료의 원리와 효과를 설명',
    format_type: '팩트체크형',
    status: '수정요청',
    result_doc_id: 'doc789ghi',
    result_doc_url: 'https://docs.google.com/document/d/doc789ghi',
    revision_count: 1,
    revision_request: '시술 가격대에 대한 내용을 추가해주세요',
    completed_at: '2025-01-11T14:30:00',
    created_by: 'staff2@company.com',
    chat_history: [
      {
        id: 'msg008',
        role: 'system',
        content: '블로그 글 생성을 시작합니다.\n\n**타겟 키워드:** 기미치료\n**주제:** 피코레이저\n**구조:** 팩트체크형',
        created_at: '2025-01-11T14:00:00',
      },
      {
        id: 'msg009',
        role: 'assistant',
        content: '블로그 글 초안을 완성했습니다.\n\n기미 치료에 대한 팩트체크형 글을 작성했습니다. 피코레이저의 원리와 기존 레이저와의 차이점, 그리고 실제 효과에 대해 의학적 근거를 바탕으로 설명했습니다.',
        created_at: '2025-01-11T14:30:00',
        doc_url: 'https://docs.google.com/document/d/doc789ghi',
        doc_id: 'doc789ghi',
      },
      {
        id: 'msg010',
        role: 'user',
        content: '시술 가격대에 대한 내용을 추가해주세요',
        created_at: '2025-01-11T15:00:00',
      },
    ],
  },
  {
    request_id: 'R20250110001',
    created_at: '2025-01-10T09:00:00',
    hospital_id: 'H001',
    hospital_name: '좋은문화병원 림프부종센터',
    target_keyword: '하지림프부종',
    topic_keyword: '압박스타킹',
    purpose: '하지 림프부종 환자들에게 올바른 압박스타킹 착용 방법과 관리법을 안내',
    format_type: '칼럼형',
    status: '수정완료',
    result_doc_id: 'doc101jkl',
    result_doc_url: 'https://docs.google.com/document/d/doc101jkl',
    revision_count: 2,
    completed_at: '2025-01-10T11:00:00',
    created_by: 'staff@company.com',
    chat_history: [
      {
        id: 'msg011',
        role: 'system',
        content: '블로그 글 생성을 시작합니다.\n\n**타겟 키워드:** 하지림프부종\n**주제:** 압박스타킹\n**구조:** 칼럼형',
        created_at: '2025-01-10T09:00:00',
      },
      {
        id: 'msg012',
        role: 'assistant',
        content: '블로그 글 초안을 완성했습니다.\n\n하지 림프부종과 압박스타킹에 대한 칼럼형 글을 작성했습니다. 전문의 관점에서 올바른 착용법과 관리 팁을 안내했습니다.',
        created_at: '2025-01-10T09:30:00',
        doc_url: 'https://docs.google.com/document/d/doc101jkl_v1',
        doc_id: 'doc101jkl_v1',
      },
      {
        id: 'msg013',
        role: 'user',
        content: '압박스타킹 착용 시 주의사항을 더 자세히 설명해주세요',
        created_at: '2025-01-10T09:45:00',
      },
      {
        id: 'msg014',
        role: 'assistant',
        content: '주의사항 부분을 보강했습니다.\n\n착용 전 피부 상태 확인, 올바른 착용 순서, 착용 시간, 세탁 및 관리 방법 등을 더 상세하게 추가했습니다.',
        created_at: '2025-01-10T10:15:00',
        doc_url: 'https://docs.google.com/document/d/doc101jkl_v2',
        doc_id: 'doc101jkl_v2',
      },
      {
        id: 'msg015',
        role: 'user',
        content: '마지막에 병원 상담 유도 문구를 추가해주세요',
        created_at: '2025-01-10T10:30:00',
      },
      {
        id: 'msg016',
        role: 'assistant',
        content: '상담 유도 문구를 추가했습니다.\n\n글의 마무리 부분에 자연스럽게 병원 상담을 유도하는 문구를 넣었습니다. "더 자세한 상담이 필요하시면..." 형태로 부담스럽지 않게 작성했습니다.',
        created_at: '2025-01-10T11:00:00',
        doc_url: 'https://docs.google.com/document/d/doc101jkl',
        doc_id: 'doc101jkl',
      },
    ],
  },
];

// Mock 사용자 데이터 (현재 로그인 사용자)
export const mockCurrentUser: User = {
  id: 'U001',
  email: 'admin@company.com',
  name: '관리자',
  avatar: undefined,
  role: 'admin',
  status: 'approved',
  created_at: '2025-01-01T09:00:00',
  approved_at: '2025-01-01T09:00:00',
};

// Mock 전체 사용자 목록 (관리자용)
export const mockUsers: User[] = [
  {
    id: 'U001',
    email: 'admin@company.com',
    name: '관리자',
    avatar: undefined,
    role: 'admin',
    status: 'approved',
    created_at: '2025-01-01T09:00:00',
    approved_at: '2025-01-01T09:00:00',
  },
  {
    id: 'U002',
    email: 'staff@company.com',
    name: '김담당',
    avatar: undefined,
    role: 'user',
    status: 'approved',
    created_at: '2025-01-05T10:00:00',
    approved_at: '2025-01-05T10:30:00',
  },
  {
    id: 'U003',
    email: 'staff2@company.com',
    name: '이마케터',
    avatar: undefined,
    role: 'user',
    status: 'approved',
    created_at: '2025-01-07T11:00:00',
    approved_at: '2025-01-07T11:15:00',
  },
  {
    id: 'U004',
    email: 'newbie@company.com',
    name: '박신입',
    avatar: undefined,
    role: 'user',
    status: 'pending',
    created_at: '2025-01-12T09:00:00',
  },
  {
    id: 'U005',
    email: 'former@company.com',
    name: '최퇴사',
    avatar: undefined,
    role: 'user',
    status: 'blocked',
    created_at: '2025-01-03T10:00:00',
    approved_at: '2025-01-03T10:30:00',
    blocked_at: '2025-01-10T17:00:00',
  },
];

// 글 구조 옵션 (할루시네이션 방지를 위해 가상 사례 유발 옵션 제거)
export const formatOptions: { value: FormatType; label: string; description: string }[] = [
  { value: 'Q&A형', label: 'Q&A형', description: '질문과 답변 형식으로 정보 전달' },
  { value: '정보제공형', label: '정보제공형', description: '치료/시술에 대한 일반적인 의학 정보 전달' },
  { value: '치료과정 안내형', label: '치료과정 안내형', description: '치료 과정을 단계별로 일반적인 관점에서 설명' },
  { value: '비교분석형', label: '비교분석형', description: '여러 치료법의 장단점을 객관적으로 비교' },
  { value: '팩트체크형', label: '팩트체크형', description: '의학적 사실을 근거로 한 정보 전달' },
  { value: '칼럼형', label: '칼럼형', description: '전문가 관점의 칼럼 형식' },
  { value: '기타', label: '기타', description: '자유 형식으로 작성' },
];
